version: '3.4'
services:
  
  fuse-analysis-cellfie:
    build:
      context: .
    restart: always
    environment:
      FUSE_HOST: $FUSE_HOST
      FUSE_PORT: $FUSE_PORT
      FUSE_VERSION: $FUSE_VERSION
    ports:
      - $API_PORT:8080

    
