apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
    app.kubernetes.io/instance: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
    service-type: webserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
      app.kubernetes.io/instance: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
      service-type: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
        app.kubernetes.io/instance: {{ include "fuse-analysis-cellfie.fullname" . }}-deployment
        service-type: webserver
    spec:
      containers:
        - name: {{ include "fuse-analysis-cellfie.fullname" . }}-server
          image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}
          imagePullPolicy: Always
          env:
            - name: "DATABASE_URL"
              value: "postgresql+psycopg2://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "fuse-analysis-cellfie.fullname" . }}-postgres:5432/{{ .Values.postgres.dbName }}"
            - name: "REDIS_HOST"
              value: "{{ include "fuse-analysis-cellfie.fullname" . }}-redis"
            - name: "REDIS_PORT"
              value: "{{ .Values.redis.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.webserver.service.port }}
              protocol: TCP
          command:
            - 'uvicorn'
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.webserver.service.port }}"
            - "--workers"
            - "4"
            - "app.main:APP"
#          volumeMounts:
#            - name: fa-cellfie-logs-vol
#              mountPath: /repo/fa-cellfie/logs
#            - name: fa-cellfie-queue-files-vol
#              mountPath: /repo/fa-cellfie/queue-files
          resources:
            {{- toYaml .Values.webserver.service.resources | nindent 12 }}
#      volumes:
#        - name: fa-cellfie-logs-vol
#          persistentVolumeClaim:
#            claimName: {{ include "fuse-analysis-cellfie.fullname" . }}-logs-pvc
#        - name: fa-cellfie-queue-files-vol
#          persistentVolumeClaim:
#            claimName: {{ include "fuse-analysis-cellfie.fullname" . }}-queue-files-pvc

