apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fuse-analysis-cellfie.fullname" . }}-postgres
  labels:
    {{- include "fuse-analysis-cellfie.labels" . | nindent 4 }}
    type: dbms
spec:
  serviceName: {{ include "fuse-analysis-cellfie.fullname" . }}-postgres
  selector:
    matchLabels:
      {{- include "fuse-analysis-cellfie.selectorLabels" . | nindent 6 }}
      type: dbms
  template:
    metadata:
      {{- with .Values.postgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuse-analysis-cellfie.selectorLabels" . | nindent 8 }}
        type: dbms
    spec:
      {{- with .Values.postgres.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user }}
          - name: POSTGRES_DB
            value: {{ .Values.postgres.dbName }}
          ports:
            - name: postgres-port
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgresdata
              name: {{ include "fuse-analysis-cellfie.fullname" . }}-postgres-data
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 400Mi
  volumeClaimTemplates:
    - metadata:
        name: {{ include "fuse-analysis-cellfie.fullname" . }}-postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
