replicaCount: 1

webserver:
  image:
    repository: jdr0887/fuse-analysis-cellfie
    tag: "0.1"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: 2Gi
      cpu: 2000m
    limits:
      memory: 2Gi
      cpu: 4000m

redis:
  dataSize: 2Gi
  image:
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  storage:
    size: 2Gi
  service:
    type: ClusterIP
    port: 6379
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 2000m
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgres:
  image:
    repository: postgres
    tag: "latest"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  storage:
    size: 2Gi
  user: fa
  dbName: "fa"
  password: "fa"
  service:
    type: ClusterIP
    port: 5432
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m

ingress:
  enabled: true
  host: "fa-cellfie.renci.org"
